#!/usr/bin/env bash

# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

# Create the main HTML page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Create custom_404 page
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure redirection
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Configure custom 404 page
sudo sed -i '/^}$/i \ \n\terror_page 404 \/custom_404.html;' /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx reload

# Check Nginx configuration syntax
sudo nginx -t

# If the syntax is okay, reload Nginx
if sudo nginx -t; then
    # If the syntax is okay, restart Nginx
    sudo service nginx restart
else
    echo "Nginx configuration test failed. Please check your configuration."
fi