#!/usr/bin/env bash
# Duplicate web-01 to web-02

# Uncomment to see the script run in action
# set -x

echo -e "Updating and doing some minor checks...\n"

function install() {
  command -v "$1" &> /dev/null

  if [ $? -ne 0 ]; then
    echo -e "Installing: $1\n"
    sudo apt-get update -y -qq && \
      sudo apt-get install -y "$1" -qq
    echo -e "\n"
  else
    echo -e "${1} is already installed.\n"
  fi
}

install nginx # Install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
  sudo chown -R "$USER":"$USER" /var/www
  sudo chmod -R 755 /var/www
else
  sudo mkdir -p /var/www
  sudo chown -R "$USER":"$USER" /var/www
  sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
  if ! [ -d "$dir" ]; then
    mkdir -p "$dir"
  fi
done

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create new error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Function to configure server
configure_server() {
  local server_config
  server_config="
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html index.htm index.nginx-debian.html;
  server_name _;
  add_header X-Served-By \$hostname;
  location / {
    try_files \$uri \$uri/ =404;
  }
  if (\$request_filename ~ redirect_me) {
    rewrite ^ https://www.linkedin.com/in/emmanuel-paul-391089225 permanent;
  }
  error_page 404 /error_404.html;
  location = /error_404.html {
    internal;
  }
}"
  echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
}

configure_server

# Check if Nginx is running and restart if necessary
if ! sudo systemctl is-active --quiet nginx; then
  sudo service nginx start
else
  sudo service nginx restart
fi

# rewrite ^ https://www.linkedin.com/in/emmanuel-paul-391089225 permanent;
