#!/usr/bin/env bash

# Install and configure HAProxy load balancer

set -e # Exit script on error if any command fails

# Update and upgrade system packages
sudo apt-get update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Create a backup of the original HAProxy configuration file (recommended)
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOF >> /etc/haproxy/haproxy.cfg
# Global settings
global
  log /dev/log local0 notice
  maxconn 2000
  user haproxy
  group haproxy
  daemon

# Default settings for frontends and backends
defaults
  mode http
  option httplog
  option dontlognull
  timeout connect 5s
  timeout client 10s
  timeout server 30s

# Frontend configuration
frontend haproxy_balancer
  bind *:80
  default_backend webservers

# Backend configuration
backend webservers
  balance roundrobin
  server 183438-web-01 54.173.0.235:80 check
  server 183438-web-02 18.234.249.203:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy

# Print information about the configured servers
echo "HAProxy configured successfully."
echo "Configured servers: [web-01, web-02]"
