#!/usr/bin/env bash
# Install and configure HAProxy load balancer

echo -e "Updating and performing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    # Check if the command is not installed
    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "$1 is already installed.\n"
    fi
}

install haproxy  # Install HAProxy

echo -e "\nSetting up some minor configurations...\n"

# Backup the default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend haproxy_balancer
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 183438-web-01 54.173.0.235:80 check
    server 183438-web-02 18.234.249.203:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configuration complete - Round-robin load balancing enabled on web-01 & web-02"

# Check if HAProxy is running and start or restart accordingly
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
