#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.
if [ "$#" -gt 0 ]; then
    # Ping the IP address 5 times
    ping "$1" -c 5  
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

