#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the available sites configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
