#!/usr/bin/env bash
# Displays "Best School" 10 times using only while loop

# Initialize counter variable
counter=0

# Define the loop condition
while [ "$counter" -lt 10 ]; do
	echo "Best School"

	# Increment the counter
	counter=$((counter + 1))
done
