#!/usr/bin/env bash
# Displays "Best School" 10 times, but for the 9th iteration,
# displays "Best School and then "Hi" on a new line.

# Intialize counter variable
counter=0

# Define the loop condition
while [ "$counter" -lt 10 ]; do
	if [ "$counter" -eq 8 ]; then
		# 9th iteration
		echo "Best School"
		echo "Hi"
	else
		# other iterations
		echo "Best School"
	fi
	# Increment the counter
	counter=$((counter + 1))
done
