#!/usr/bin/env bash

: <<'COMMENT'
counter = 1

while counter <= 10:
	if counter == 4:
# Display "Bad Luck" for the 4th iteration
	elif counter == 8:
# Display "Good Luck" for the 8th iteration
	else:
# Display "Best School" for other iterations

# Increment the counter
	counter = counter + 1
COMMENT

# Loop from 1 to 10 and displays:
# "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Best School" for the other iterations

# Iniatialize counter variable
counter=1

# Define the loop condition
while [ "$counter" -le 10 ]; do
	if [ "$counter" -eq 4 ]; then
		echo "bad luck"
	elif [ "$counter" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	# Increment the counter
	counter=$((counter + 1))
done
