#!/usr/bin/env bash


# Loop from 1 to 10 and displays:
# "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Best School" for the other iterations

# Iniatialize counter variable
counter=0

# Define the loop condition
while [ "$counter" -lt 10 ]; do
	if [ "$counter" -eq 4 ]; then
		echo "bad luck"
	elif [ "$counter" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	# Increment the counter
	counter=$((counter + 1))
done
