#!/usr/bin/env bash

:<<'COMMENT'
counter = 1

while counter <= 20:
    case counter of
        4:
            # Display "4" and then "Bad Luck from China"
        9:
            # Display "9" and then "Bad Luck from Japan"
        17:
            # Display "17" and then "Bad Luck from Italy"
        default:
            # Display the current number
    end case

    # Increment the counter
    counter = counter + 1
COMMENT

counter=1

while [ "$counter" -le 20 ]; do
	case $counter in
		4)
			echo "$counter bad luck for China"
			;;
		9)
			echo "$counter bad luck from Japan"
			;;
		17)
			echo "$counter bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
	esac

	# Increment the counter
	counter=$((counter + 1))
done
