#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
#    hours from 0 to 12
#    minutes from 1 to 59

hour=0

while [ "$hour" -le 12 ]; do
    echo "Hour: $hour"
    minute=1
    while [ "$minute" -le 59 ]; do
        # Display the current time (minute)
        echo "$minute"

        # Increment the minute
        minute=$((minute + 1))
    done

    # Increment the hour
    hour=$((hour + 1))
done