#!/usr/bin/env bash
# Bash script that display:
#   The content of the current directory
#   In a list format
#   Where only yhe part of the name after the first dash is displayed
for file in *; do
    #check if file is mot hidden
    if [[ "$file" != .* ]]; then
        #Extract part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)
        
        # Display the extracted part in a list format
        echo "$name_part"
    fi
done
