#!/usr/bin/env bash
# Display information about the `school` file

if [ -e "school" ]; then
    # "school" file exists
    echo "school file exists"

    if [ -s "school" ]; then
        # "school" file is not empty
        echo "school file is not empty"
    else
        # "school" file is empty
        echo "school file is empty"
    fi

    if [ -f "school" ]; then
        # "school" is a regular file
        echo "school is a regular file"
    fi

else
    # "school" file does not exist
    echo "school file does not exist"

fi