#!/usr/bin/env bash

# Exit the shell when (some) commands fail
set -e

# Update and install UFW if not already installed
sudo apt update -y
sudo apt install ufw -y

# Enable UFW
sudo ufw enable

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Deny all other incoming traffic
sudo ufw default deny incoming

# Allow default outgoing traffic
sudo ufw default allow outgoing

sudo ufw status verbose
