#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
#   - `localhost` resolves to `127.0.0.2`
#   - `facebook.com` resolves to `8.8.8.8.`

# Backup
cp /etc/hosts /etc/hosts.bak

# Modify host file
# Using temp file since /etc/hosts may be mounted by Docker
cat << EOF > /tmp/hosts
127.0.0.1 localhost
127.0.0.2 localhost

8.8.8.8 facebook.com
EOF

# Move tmp file to /etc/hosts
# Rename fails if in use, hence temp file
mv /tmp/hosts /etc/hosts

# Validate changes
ping -c 1 localhost # Shove resolve to 127.0.0.2
ping -c 1 facebook.com # Should resolve to 8.8.8.8