#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
#   - `localhost` resolves to `127.0.0.2`
#   - `facebook.com` resolves to `8.8.8.8.`

# Backup
sudo cp /etc/hosts /root/hosts.new

# Modify the temporary hosts file
sed -i 's/127.0.0.1/127.0.0.2/' /root/hosts.new
sed -i '1s/^/8.8.8.8 facebook.com\n/' /root/hosts.new

# Replace the original /etc/hosts with the modified version
sudo cp -f /root/hosts.new /etc/hosts